include: package:lint/analysis_options.yaml
analyzer:
  exclude:
  - "**/*.g.dart"
  - "**/*.gr.dart"
  - "**/*.iconfig.dart"
  - "**/*.freezed.dart"
  - "**/firebase_auth_facade.dart"
  # - 'bin/cache/**'
  # - "lib/**/*.g.dart"
  # - "lib/**/*.gr.dart"
  # - "lib/**/*.freezed.dart"
  # - "lib/injection.iconfig.dart"
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    missing_required_param: error
    # treat missing returns as a warning (not a hint)
    missing_return: error
    # allow having TODOs in the code
    todo: ignore
    # Ignore analyzer hints for updating pubspecs when using Future or
    # Stream and not importing dart:async
    sdk_version_async_exported_from_core: ignore

linter:
  rules:
   - prefer_relative_imports
